---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
spec:
  chartRef:
    kind: OCIRepository
    name: openbao
  interval: 1h
  values:
    server:
      standalone:
        enabled: true
      dataStorage:
        enabled: true
        size: 5Gi
    injector:
      enabled: false
